//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceMobileSMR.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conducteur
    {
        public long Cdr_Id { get; set; }
        public string Cdr_adresseMail { get; set; }
    }
}
