//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceMobileSMR.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordonnee
    {
        public long Coo_Id { get; set; }
        public System.DateTime Coo_Date { get; set; }
        public long Coo_Long { get; set; }
        public long Coo_Lat { get; set; }
    }
}
